Repository qiboteam/qiboml, pull requests merged in 2025-07, with the labels that each got.

#121 Add tutorial on real time error mitigation to documentation
  doc/source/index.rst
  src/qiboml/models/decoding.py
  tutorials/data_reuploading.ipynb
  tutorials/figures/cdr_scheme.png
  tutorials/real_time_error_mitigation.ipynb
Labels: documentation

#130 Small change to `PyTorchBackend.set_device`
  src/qiboml/backends/pytorch.py
Labels: bug

#114 Add Variational Quantum Linear Solver (VQLS) Tutorial
  doc/source/index.rst
  doc/source/tutorials/figures/VQLS_Diagram.png
  doc/source/tutorials/variational_quantum_linear_solver.ipynb
  src/qiboml/models/decoding.py
  tests/test_interfaces.py
  tests/test_models_decoding.py
  tutorials/figures/VQLS_Diagram.png
  tutorials/variational_quantum_linear_solver.ipynb
Labels: enhancement, run-workflow
